apiVersion: v1
kind: Service
metadata:
  name: cloud-native-proj-svc
  namespace: nju31
spec:
  type: NodePort
  selector:
    app: cloud-native-proj
  ports:
    - nodePort: 30001 # host's port,集群外部访问端口
      protocol: TCP
      port: 8888 # service's port,集群内部访问端口
      targetPort: 8080 # target pod's port,服务最终端口，所有流量流至该端口，和